version: '3'

services:

  main:
    image: tutum/lamp
    networks:
      - common
    volumes:
      # webapp code
      - ./app:/var/www/html
    env_file:
      - host.env
    logging:
      driver: none
