# Project structure file
#
# @project maintenance
# @author demmonico
# @version v0.1.0

version: '3'

services:

  app:
    image: tutum/lamp
    networks:
      - common
    volumes:
      # webapp code
      - ./app/src:/var/www/html
    env_file:
      - host.env
    logging:
      driver: none
