name: {{ DM_NAME }}
network:
  host_port: {{ HOST_PORT }}
  hosts:
    - {{ HOST_NAME }}
container:
  cmd_aliases:
    - laravel/phpunit=/var/www/html/vendor/bin/phpunit -c /var/www/html/phpunit.xml
    - moodle/cacheclear=php /var/www/html/admin/cli/purge_caches.php && echo 'Done'
