# Project structure file
#
# @project maintenance
# @author demmonico
# @version v0.1.0

version: '3'

services:
  proxy:
    build: .
    ports:
      - "${DM_HOST_PORT}:80"
    networks:
      - common
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    env_file:
      - host.env

networks:
  common:
    driver: bridge
