version: '3'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
#      - "80:80"
#      - "8080:80"
#      - "443:443"
      - "${DM_HOST_PORT}:80"
    networks:
      - common
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./default_location:/etc/nginx/vhost.d/default_location:ro
      - ./custom.conf:/etc/nginx/conf.d/custom.conf:ro
      - ./nginx.tmpl:/app/nginx.tmpl:ro
    env_file:
      - host.env

networks:
  common:
    driver: bridge
