version: '3'

services:
  proxy:
    image:
      jwilder/nginx-proxy
    container_name:
      proxy
    ports:
      - "80:80"
#      - "8080:80"
#      - "443:443"
    networks:
      - common
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./default_location:/etc/nginx/vhost.d/default_location:ro

networks:
  common:
    driver: bridge
