# Main docker-compose.yml file of the project
#
# @project test
# @author demmonico
# @version v0.5.0

version: '3'

services:

  app:
    image: demmonico/ubuntu-apache-php:7.0
    networks:
      # connect to private internal project network
      - internal
    links:
      # create alias for DB container (db container name : internal alias at app container)
      - db:db
    environment:
      # alias name of internal DB host
      - DB_HOST=db

  db:
    image: demmonico/ubuntu-mariadb:10.1
    volumes:
      # db tables
      - ./db/data:/var/lib/mysql
    networks:
      # connect to private internal project network
      - internal

networks:
  # connect to private internal project network
  internal:
    driver: bridge
